=== lsmatott/ostrich-swmm/ostrich_swmm/data/schemas/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "OSTRICH-SWMM Config",
    "description": "A configuration for the OSTRICH-SWMM package.",
    "type": "object",
    "properties": {
        "binary_output_path": {
            "type": "string"
        },
        "input_template_path": {
            "type": "string",
            "minLength": 1
        },
        "input_parameters_path": {
            "type": "string",
            "minLength": 1
        },
        "input_path": {
            "type": "string",
            "minLength": 1
        },
        "report_output_path": {
            "type": "string",
            "minLength": 1
        },
        "swmm_path": {
            "type": "string",
            "minLength": 1
        },
        "summary_dir": {
            "type": "string"
        },
        "extract": {
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/extract_step"
                    }
                }
            },
            "required": [
                "steps"
            ]
        }
    },
    "definitions": {
        "extract_step": {
            "type": "object",
            "oneOf": [
                {
                    "$ref": "#/definitions/node_extract_step"
                }
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "type"
            ]
        },
        "node_extract_step": {
            "type": "object",
            "properties": {
                "event_threshold_flow_rate": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "pattern": "^node$"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output_path": {
                    "type": "string"
                },
                "statistics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_extract_statistic"
                    }
                }
            },
            "required": [
                "statistics",
                "nodes",
                "output_path"
            ]
        },
        "node_extract_statistic": {
            "enum": [
                "node_name",
                "num_flow_events",
                "total_flow_volume",
                "total_flow_duration",
                "first_flow_start",
                "first_flow_end",
                "first_flow_duration",
                "first_flow_volume",
                "last_flow_start",
                "last_flow_end",
                "last_flow_duration",
                "last_flow_volume",
                "max_volume_flow_start",
                "max_volume_flow_end",
                "max_volume_flow_duration",
                "max_volume_flow_volume",
                "max_duration_flow_start",
                "max_duration_flow_end",
                "max_duration_flow_duration",
                "max_duration_flow_volume"
            ]
        }
    }
}

=== lsmatott/ostrich-swmm/examples/epa21/ostrich-swmm-config.json
{
    "binary_output_path": "epa21_model.out",
    "input_template_path": "epa21_model.tpl",
    "input_parameters_path": "epa21_lid_input_parameters.json",
    "input_path": "epa21_model.inp",
    "report_output_path": "epa21_model.rpt",
    "summary_dir": ".",
    "swmm_path": "./swmm5.sh",
    "extract": {
        "steps": [
            {
                "type": "node",
                "enabled": true,
                "output_path": "epa21_model_nodes.csv",
                "statistics": [
                    "node_name",
                    "num_flow_events",
                    "total_flow_volume",
                    "total_flow_duration",
                    "first_flow_start",
                    "first_flow_end",
                    "first_flow_duration",
                    "first_flow_volume",
                    "last_flow_start",
                    "last_flow_end",
                    "last_flow_duration",
                    "last_flow_volume",
                    "max_volume_flow_start",
                    "max_volume_flow_end",
                    "max_volume_flow_duration",
                    "max_volume_flow_volume",
                    "max_duration_flow_start",
                    "max_duration_flow_end",
                    "max_duration_flow_duration",
                    "max_duration_flow_volume"
                ],
                "nodes": [ "OF1"
                ],
                "event_threshold_flow_rate": 0
            }
        ]
    }
}

=== lsmatott/ostrich-swmm/examples/multiple_lids/ostrich-swmm-config.json
{
    "binary_output_path": "lid_model.out",
    "input_template_path": "lid_model.tpl",
    "input_parameters_path": "lid_model_input_parameters.json",
    "input_path": "lid_model.inp",
    "report_output_path": "lid_model.rpt",
    "summary_dir": ".",
    "swmm_path": "C:\\Program Files\\EPA SWMM 5.2.0 (64-bit)\\runswmm.exe",
    "extract": {
        "steps": [
            {
                "type": "node",
                "enabled": true,
                "output_path": "lid_model_nodes.csv",
                "statistics": [
                    "node_name",
                    "num_flow_events",
                    "total_flow_volume",
                    "total_flow_duration",
                    "first_flow_start",
                    "first_flow_end",
                    "first_flow_duration",
                    "first_flow_volume",
                    "last_flow_start",
                    "last_flow_end",
                    "last_flow_duration",
                    "last_flow_volume",
                    "max_volume_flow_start",
                    "max_volume_flow_end",
                    "max_volume_flow_duration",
                    "max_volume_flow_volume",
                    "max_duration_flow_start",
                    "max_duration_flow_end",
                    "max_duration_flow_duration",
                    "max_duration_flow_volume"
                ],
                "nodes": [ "O1", "O2"
                ],
                "event_threshold_flow_rate": 0
            }
        ]
    }
}
